Modernize Indium
comp500/Indium pull request #115
Opened 2022-04-23 13:05 UTC by IMS212

FabricMC/fabric#2110 but for Indium.

2022-04-23 16:07 UTC, PepperCode1 requested changes

2022-04-23 16:07 UTC, PepperCode1 commented on src/main/java/link/infra/indium/renderer/render/BaseMeshConsumer.java
>  		if (!transform.transform(editorQuad)) {
```suggestion
		if (!transform.transform(quad)) {
```

2022-04-23 16:07 UTC, PepperCode1 commented on src/main/java/link/infra/indium/mixin/renderer/MixinItemRenderer.java
> +}
Need a newline here

2022-04-23 16:07 UTC, PepperCode1 commented on src/main/java/link/infra/indium/renderer/render/BaseFallbackConsumer.java
> +				for (final BakedQuad q : quads) {
Revert the change to an enhanced for loop; this is inconsistent with Indigo and less efficient.

2022-04-23 16:07 UTC, PepperCode1 commented on src/main/java/link/infra/indium/renderer/render/ItemRenderContext.java
> +}
Need a newline here

2022-04-23 16:24 UTC, IMS212 commented on src/main/java/link/infra/indium/renderer/render/BaseMeshConsumer.java
>  		if (!transform.transform(editorQuad)) {
Are you sure this is right?

2022-04-23 19:04 UTC, PepperCode1 approved these changes

2022-04-24 15:09 UTC, comp500 commented
```java
 * Does not implement emissive lighting for sake
 * of simplicity in the default renderer.
```
This javadoc note in `ItemRenderContext` was removed in the original Indigo PR; does it still apply to Indium with these changes or should it be removed here as well?

2022-04-24 15:30 UTC, merged